site_name: AnsibleMetrics
repo_name: GitHub
repo_url: https://github.com/radon-h2020/radon-ansible-metrics/
nav:
    - Getting Started: 
        - Quick Start: index.md
    - Metrics:
        - General:
            - Lines blank: general/LinesBlank.md
            - Lines of code: general/LinesCode.md
            - Lines of comment: general/LinesComment.md
            - Number of conditions: general/NumConditions.md
            - Number of decisions: general/NumDecisions.md
            - Number of deprecated keywords: general/NumDeprecatedKeywords.md
            - Number of keys: general/NumKeys.md
            - Number of math operations: general/NumMathOperations.md
            - Number of suspicious comments: general/NumSuspiciousComments.md
            - Number of tokens: general/NumTokens.md
            - Text entropy: general/TextEntropy.md
        - Playbook:
            - Average play size: playbook/AvgPlaySize.md
            - Average task size: playbook/AvgTaskSize.md
            - Number of blocks: playbook/NumBlocks.md
            - Number of block error handling: playbook/NumBlocksErrorHandling.md
            - Number of commands: playbook/NumCommands.md
            - Number of deprecated modules: playbook/NumDeprecatedModules.md
            - Number of distinct modules: playbook/NumDistinctModules.md
            - Number of external modules: playbook/NumExternalModules.md
            - Number of fact modules: playbook/NumFactModules.md
            - Number of file extists: playbook/NumFileExists.md
            - Number of file mode: playbook/NumFileMode.md
            - Number of file modules: playbook/NumFileModules.md
            - Number of filters: playbook/NumFilters.md
            - Number of ignore_errors: playbook/NumIgnoreErrors.md
            - Number of import_playbook: playbook/NumImportPlaybook.md
            - Number of import_role: playbook/NumImportRole.md
            - Number of import_tasks: playbook/NumImportTasks.md
            - Number of include: playbook/NumInclude.md
            - Number of include_role: playbook/NumIncludeRole.md
            - Number of include_tasks: playbook/NumIncludeTasks.md
            - Number of include_vars: playbook/NumIncludeVars.md
            - Number of lookups: playbook/NumLookups.md
            - Number of loops: playbook/NumLoops.md
            - Number of name with variables: playbook/NumNameWithVars.md
            - Number of parameters: playbook/NumParameters.md
            - Number of paths: playbook/NumPaths.md
            - Number of regex: playbook/NumRegex.md
            - Number of plays: playbook/NumPlays.md
            - Number of prompts: playbook/NumPrompts.md
            - Number of roles: playbook/NumRoles.md
            - Number of SSH: playbook/NumAuthorizedKey.md
            - Number of tasks: playbook/NumTasks.md
            - Number of unique names: playbook/NumUniqueNames.md
            - Number of urls: playbook/NumUri.md 
            - Number of variables: playbook/NumVars.md
    - About: about.md
theme: readthedocs